name: AceBook CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: cd api && npm i && cd ../frontend && npm i

      # Build the AceBook app
      - name: Build AceBook app
        run: cd frontend && npm run build

      # Run tests
      - name: Run tests
        run: |
          # Install MongoDB
          sudo apt-get update
          sudo apt-get install -y mongodb
          
          # Start MongoDB
          sudo systemctl start mongodb
          sudo systemctl status mongodb
          
          # Set up environment variables
          echo 'VITE_BACKEND_URL="http://localhost:3000"' > frontend/.env
          echo 'MONGODB_URL="mongodb://0.0.0.0/acebook"' > api/.env
          echo 'NODE_ENV="development"' >> api/.env
          echo 'JWT_SECRET="secret"' >> api/.env
          
          # Run tests
          cd api && npm test -- --watchAll=false
          cd ../frontend && npm test -- --watchAll=false

      # Lint your code
      # Uncomment the following lines if you use ESLint
      - name: Lint code
        run: cd api && npm run lint && cd ../frontend && npm run lint
